management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  data:
    mongodb:
      database: oomall
      username: demouser
      password: '123456'
      authentication-database: oomall
  jackson:
    time-zone: GMT+8

# MongoDB 的副本集配置
replicaset:
  mongodb:
    replica-set: rs0
    read-preference: nearest
    hosts: mongo1:27017,mongo1:27017,mongo1:27017

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG


