management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  data:
    mongodb:
      database: oomall
      username: demouser
      password: '123456'
      authentication-database: oomall
      hosts: mongo1:27017,mongo2:27018,mongo3:27019
      replica-set: rs0
  jackson:
    time-zone: GMT+8

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG


